config/routes.rb
Rails.application.routes.draw do

  get 'users/profil', "users#profil"
  get 'users/update'
  get 'items/index'
  get 'items/create'
  get 'items/update'
  get 'items/delete'
  get 'items/new'
  get 'items/show'
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :items
  resources :carts
  resources :users do 
    resources :avatars, only: [:create]
  end
  resources :orders
  root "items#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    has_many :orders
    has_many :items, through: :orders
end

app/models/item.rb
class Item < ApplicationRecord
	validates :title, presence: true,
		length: { in: 4..150 }

	validates :description, presence: true,
		length: { in: 4..1000 }

	validates :price, presence: true,
		:if => :price_validation

	has_many :cart_items
	has_many :carts, through: :cart_items

	def price_validation
		if self.price.blank?
			errors.add(:message, "Price can't be blank")
		elsif self.price < 1 || self.price > 1000
			errors.add(:message, "Price must be between 1 and 1000")
		end
	end
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :cart
    belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   belongs_to :cart, optional: true
   has_many :carts
   has_many :orders, through: :carts
   has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    helper_method :resource_name, :resource, :devise_mapping, :resource_class


    def resource_name
      :user
    end

    def resource
      @resource ||= User.new
    end

    def resource_class
      User
    end

    def devise_mapping
      @devise_mapping ||= Devise.mappings[:user]
    end

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:account_update, except: [:password], keys: [:firstname, :lastname, :description])
    end


    private

     def authenticate_user
       unless current_user
         flash[:danger] = "Vous devez vous connecte !"
         redirect_to new_user_session_path
       end
     end

 end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
    def create
        @user = current_user
        if params[:avatar]
            @user.avatar.attach(params[:avatar])
            redirect_to users_profil_path
        else
           redirect_to users_profil_path, :flash => { :success => "Votre profil est à jour" }
        end
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

    before_action :authenticate_user

    def index
        current_cart = Cart.find_by(:user => current_user, :status => "on")

        if current_cart
            @cart_items = current_cart.orders
            quantity_total(@cart_items)
            price_total(@cart_items)
        end
    end

    def create
        current_cart = Cart.find_by(:user => current_user, :status => "on")
        item = Item.find(params[:id])

        if current_cart
            if current_cart.orders
                current_cart.orders.each do |order|
                    if order.item.id == item.id
                        @reponse = true
                        @order = order
                    end
                end
                if @reponse == true
                        @order.quantity = @order.quantity + 1 
                        @order.save 
                else
                    order = Order.create(:cart => current_cart, :item => item, :quantity => params[:quantity])
                end
            end       
        end

        if not current_cart
            current_cart = Cart.create(:user => current_user, :status => "on")
            order = Order.create(:cart => current_cart, :item => item, :quantity => params[:quantity])
        end

        redirect_to '/', :flash => {:success => 'Produit ajouté au panier.'}

    end

    def update

    end

    def destroy

    end

    def quantity_total(orders)
        cart_items_to_sum = orders
        @quantity_total = 0
        cart_items_to_sum.each do |item|
            @quantity_total = @quantity_total + item.quantity
        end
        return @quantity_total
    end

    def price_total(orders)
        cart_items_to_sum = orders
        @price_total = 0

        cart_items_to_sum.each do |product|
            each_line_price = product.quantity * product.item.price
            @price_total =  @price_total + each_line_price
        end
        return @price_total
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @item = Item.all
  end

  def show
      @current_item = Item.find(params[:id])
  end

  def new

  end

  def create

  end

  def edit

  end

  def update

  end

  def destroy

  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :authenticate_user

    def create

        if UserMailer.order_email(current_user).deliver_now
            current_cart = Cart.find_by(:user => current_user, :status => "on")
            current_cart.status = "done"
            current_cart.save

            redirect_to '/', :flash => { :success => "Votre commande a été passé. Un email contenant les détails de votre commande vous a été envoyé." }
        end

    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    before_action :configure_permitted_parameters, if: :devise_controller?	
   
    protected  
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:account_update, except: [:password], keys: [:firstname, :lastname, :description])

    end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def profil
        @user = current_user
    end

    def update
        @user = current_user.update
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/index.html.erb
<div class="container card-bg mt-5 mb-5">
    <div class="row p-4">
        <div class="col-sm-12">
            <h1 class="text-center mb-5"> Contenu du panier</h1>

             <% if @cart_items %>
                <table class="table table-striped table-hover">
                    <thead>
                        <tr class="bg-primary text-white">
                            <th> Image </th>
                            <th> Title </th>
                            <th> Description </th>
                            <th> Quantity</th>
                            <th> Prix(total) </th>
                        </tr>
                    </thead>

                    <tbody>
                        <% @cart_items.each do |i| %>
                            <tr>
                                <td> <%= image_tag i.item.image_url, width: 50, class: '' %></td>
                                <td> <%= i.item.title%> </td>
                                <td> <%= i.item.description %> </td>
                                <td> <%= i.quantity %></td>
                                <td> <%= number_to_currency i.item.price * i.quantity, unit: " AR", separator: ",", format: "%n%u" %> </td>
                            </tr>
                        <% end %>
                        <tr class="bg-yellow">
                            <th> Total </th>
                            <td></td>
                            <td></td>
                            <td> <%= @quantity_total %> </td>
                            <td> <%= number_to_currency @price_total, unit: " AR", separator: ",", format: "%n%u" %> </td>
                        </tr>
                    </tbody>
                </table>

            <%= link_to 'Passer la commande', orders_path, method: 'post', class: 'btn btn-info mt-4 float-right' %>

        <% else %>
            <h3 class="text-center text-muted">Panier vide</h3>
        <% end %>

        </div>
    </div>
</div>

app/views/items/index.html.erb
<!-- start banner Area -->
<section class="banner-area relative" id="home">
  <div class="container">
    <div class="overlay overlay-bg"></div>
    <div class="row fullscreen d-flex align-items-center justify-content-start">
      <div class="banner-content col-lg-8 col-md-12">
        <h1 class="text-uppercase">
          Adoptes-nous. <br>
          Nous avons besoins de votre aides.		
        </h1>
        <p class="text-white sub-head">
         Boutique en ligne spécialiste du chat d'intérieur. Retrouvez nos accessoires pour chat, une sélection d'alimentation naturelle pour chat et nos conseils.
        </p>
      </div>											
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start process Area -->
  <section class="process-area section-gap">
    <div class="container text-center">
      <div class="row d-flex justify-content-center">
        <div class="menu-content pb-60 col-lg-8">
          <div class="title text-center">
            <h1 class="mb-10">Guide</h1>
            <p>Who are in extremely love with eco friendly system.</p>
          </div>
        </div>
      </div>					
      <div class="row justify-content-center">
        <div class="col-lg-3 col-md-6 m-1 p-3 card-bg">
          <div class="single-process">
            <span class="lnr lnr-thumbs-up"></span>
              <h4 class="m">
                Selectionné votre Chaton
              </h4>
            <p>
              inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct.
            </p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 m-1 p-3 card-bg">
          <div class="single-process">
            <span class="lnr lnr-user"></span>
              <h4 class="m">
                Aller sur le menu Panier
              </h4>
            <p>
              inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct.
            </p>
          </div>
        </div>
        <div class="col-lg-3 col-md-6 m-1 p-3 card-bg">
          <div class="single-process">
            <span class="lnr lnr-license"></span>
              <h4 class="m">
                Faite votre achat
              </h4>
            <p>
              inappropriate behavior is often laughed off as “boys will be boys,” women face higher conduct.
            </p>
          </div>
        </div>
																	
      </div>
    </div>	
  </section>
<!-- End process Area -->
			

<div class="p-5 neo-bg">
  <div class="row">

  <% @item.each do |i| %>
    <div class="col-sm-4 mb-4 card-shadow">

      <div class="card-bg h-100 shadow">
        <a href="<%= item_path(i.id) %>"><%= image_tag i.image_url, width: '100%', style:"border-radius: 1em 1em 0em 0em"  %></a>
        <div class="card-body" style="border-top:3px solid #ffc107;">
            <h4 class="card-title">
                <%= i.title %>
                <span class="float-right text-muted"><%= i.price * 50 %> Ar</span>
            </h4>
            <p class="card-text"><%= i.description %></p>
            <%= form_tag carts_path, method: "post" do %>
              <div class="form-row">
                <div class="col">
                  <div class="input-group mb-2">
                    <div class="input-group-prepend">
                      <div class="input-group-text">Quantity</div>
                    </div>
                    <%= number_field_tag 'quantity', 1, :class => 'form-control' %>
                    <%= hidden_field_tag 'id', i.id %>
                  </div>
                </div>
              </div>
              <%= link_to 'Voir', item_path(i.id), class: "btn btn-info" %>
              <%= submit_tag "Ajouter au panier", class: 'btn btn-outline-primary float-right' %>
            <% end %>
            <span class="entourer2">
            </span>
        </div>
      </div>

    </div>
    <% end %>
  </div>
</div>

	<!-- Start calltoaction Area -->
			<section class="calltoaction-area section-gap relative">
				<div class="container">
					<div class="overlay overlay-bg"></div>						
					<div class="row align-items-center justify-content-center">
						<h1 class="text-white">Un petit projet sur "The Hacking Project"</h1>
						<p class="text-white">
               Une équipes de 6 personnes pour réaliser ce site E-commerce durant 1 semaines.
            </p>
						<div class="buttons d-flex flex-row">
							<a href="https://github.com/tsiryJL" class="primary-btn text-uppercase">Visiter mon compte Github</a>
							<a href="https://www.thehackingproject.org/" class="primary-btn text-uppercase">The Hacking Project</a>
						</div>
					</div>
				</div>	
			</section>
			<!-- End calltoaction Area -->

app/views/items/show.html.erb
<br>
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <%= image_tag @current_item.image_url, width: '100%' %>
        </div>
        <div class="col-sm-6 p-4 card-bg" style="align-self: center;">
            <h3 class="pl-2 t"><%= @current_item.title %></h3>
            <table class="table table-hover">
                <tr>
                    <th>Prix</th>
                    <td><%= @current_item.price %> Ar</td>
                </tr>
                <tr>
                    <th>Description</th>
                    <td><%= @current_item.description %></td>
                </tr>
            </table>
            <hr>
            <%= form_tag carts_path, method: "post" do %>
              <div class="form-row">
                <div class="col-4">
                  <div class="input-group mb-2">
                    <div class="input-group-prepend">
                      <div class="input-group-text">Quantity</div>
                    </div>
                    <%= number_field_tag 'quantity', 1, :class => 'form-control' %>
                    <%= hidden_field_tag 'id', @current_item.id %>
                  </div>
                </div>
              </div>
              <div class="text-center mt-2">
              <%= submit_tag "Ajouter au panier", class: 'btn btn-outline-info' %>
              </div>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<!-- start footer Area -->		
<footer class="footer-area">
    <div class="copyright-text">
        <div class="container">
            <div class="row footer-bottom d-flex justify-content-between">
                <p class="col-lg-8 col-sm-6 footer-text m-0 text-white">Copyright &copy;2019 | Tous droit reserver | ce site web est faite avec <i class="fa fa-heart-o" aria-hidden="true"></i> par <a href="https://tsiryjl.netlify.app" target="_blank">TsiryJL</a></p>
                <div class="col-lg-4 col-sm-6 footer-social">
                    <a href="https://web.facebook.com/tsiry.razanakoto.5/"><i class="fa fa-facebook"></i></a>
                    <a href="https://www.linkedin.com/in/tsiry-razanakoto-b035a9170/"><i class="fa fa-linkedin"></i></a>
                    <a href="https://www.instagram.com/tsiryjl/"><i class="fa fa-instagram"></i></a>
                    <a href="https://github.com/tsiryJL"><i class="fa fa-github"></i></a>
                    <a href="https://tsiryjl.netlify.app"><i class="fa fa-briefcase"></i></a>
                </div>
            </div>						
        </div>
    </div>
</footer>
<!-- End footer Area -->	

app/views/layouts/_navbar.html.erb
<header id="header" id="home">
  <div class="container main-menu">
    <div class="row align-items-center justify-content-between d-flex">
      <div id="logo">
        <a href="<%= items_path %>"><%= image_tag "logo" %></a>
      </div>
      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li class="menu-active navbar-link"><a href="<%= items_path %>">Accueil</a></li>
          <li>
          
            <a id="myCart" class="text-white navbar-link" href="<%= carts_path %>">
              <%= @quantity_total %>
              <i class="text-warning fas fa-shopping-cart"> </i> Mon panier
              <i style="color: yellow; " id="cart_n"></i>
            </a>
          </li>
         
          <% if user_signed_in? %>
                <li>
                  <%= link_to 'Modifier mon profile', edit_user_registration_path, :class => 'navbar-link' %>
                </li>
                <li>
                  <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                </li>
          <% else %>
                <li>
                  <%= link_to "S'inscrire", new_user_registration_path, :class => 'navbar-link'  %>
                </li>
                <li>
                  <%= link_to "Se connecter", new_user_session_path, :class => 'navbar-link'  %>
                </li>
          <% end %>
        </ul>
      </nav> 		
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie-edge">
    <meta name="description" content="Site E-commerce réaliser pour l'examen The Hacking Project">
    <title>The Meow Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
    <script src="https://kit.fontawesome.com/5c7c4423f6.js" crossorigin="anonymous"></script>
  </head>
  <body>
  <%= render 'layouts/navbar' %>
  <div class="flash-popup p-3">
    <% flash.each do |key, value| %>
      <div class="m-0 alert alert-<%= key %> alert-dismissible fade show" style="padding:2em 5em;" role="alert">
        <%= value %>
      </div>
    <% end %>
  </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/profil.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <table class="table table-hover">
                    <tr>
                        <th>Nom</th>
                        <td><%= @user.first_name %></td>
                    </tr>
                    <tr>
                        <th>Prenom</th>
                        <td><%= @user.last_name %></td>
                    </tr>
                    <tr>
                        <th>Description</th>
                        <td><%= @user.description %></td>
                    </tr>

                    <tr>
                        <th>Email</th>
                        <td><%= @user.email %></td>
                    </tr>
            
                
                <tr>
                    <h3>Avatar actuel</h3>
                    <%if @user.avatar.attached?%>
                    <%= image_tag @user.avatar, width: 50 ,alt: 'avatar' %>
                    <%else%>
                    <p>=== Il n'y a pas encore d'avatar lié à cet utilisateur ===</p>
                    <%end%>
                    <h3>Changer d'avatar ?</h3>
                    <%= form_tag user_avatars_path(@user), multipart: true do %>
                    <%= file_field_tag :avatar %>
                    <%= submit_tag "mettre à jour" %>
                    <% end %>
                </tr>
            </table>
        </div>
    </div>
</div>